language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip
before_install:
  - if [[ "$TRAVIS_GO_VERSION" == "tip" ]]; then go get github.com/mattn/goveralls; fi
script:
  - go test -v $(if [[ "$TRAVIS_GO_VERSION" == "tip" ]]; then printf %s '-covermode=count -coverprofile=coverage.out'; fi)
after_success:
  - if [[ "$TRAVIS_GO_VERSION" == "tip" ]]; then $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci; fi
notifications:
  email:
    recipients:
      - montana@montanaflynn.me
    on_success: change
    on_failure: always
